### ISSUE TITLE
Uncaught error TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by fmichaud** [9fv/node-repeat-until-success#5]
```json
{"name":"pigalle.microservices","hostname":"07ab819d24ad","pid":1,"widget_type":"Microservice","level":50,"msg":"Uncaught error TypeError: Cannot read property 'then' of undefined\n    at p.then.catch (/app/node_modules/repeat-until-success/lib/repeat-until-success.js:125:23)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)","time":"2018-02-14T16:48:15.396Z","v":0}
```

**Comment by fmichaud** [comment]
Fixed in [v0.1.5](https://github.com/9fv/node-repeat-until-success/tree/v0.1.5).
